services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: autoservice_clickhouse_hw
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - .:/homework:ro

volumes:
  clickhouse_data:
